### ISSUE TITLE
PWM lookup portability issue

### ISSUE THREAD

**Issue by ZenynEthridge** [Cyclone-Robosub/Propulsion_2024_CPP#7]
PWM Lookup works in wsl, but fails in windows. Cannot open the csv file in windows without an absolute path. We had fixed this briefly using cmake, but the problem reappeared for an unknown reason

**Comment by WilliamBarber** [comment]
I had a go at fixing this, but I don't have access to a WSL/Windows setup to test this on. Can you confirm?

**Comment by ZenynEthridge** [comment]
This now works in WSL and Windows VS. Thanks!
